
// Single catch for all Exception
public class Main
{
	public static void main(String[] args) {
	
	Exception arr[]={new ArithmeticException() ,
	                new NumberFormatException() ,
	                new NullPointerException() 
	};
 for (int i=0;i<=2;i++){
     try{
         throw arr[i];
     }
     catch(Exception E){
         System.out.println("caught an Exception");
     }
 }
}
}
